![JohnSnowLabs](https://nlp.johnsnowlabs.com/assets/images/logo.png)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/healthcare-nlp/08.2.Generic_Classifier.ipynb)

If you are using the `spark-nlp-jsl` library, please use this  [8.Generic_Classifier](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/8.Generic_Classifier.ipynb) notebook.

# Generic Classifier

In [ ]:
# Install the johnsnowlabs library to access Spark-OCR and Spark-NLP for Healthcare, Finance, and Legal.
! pip install -q johnsnowlabs

In [ ]:
from google.colab import files
print('Please Upload your John Snow Labs License using the button below')
license_keys = files.upload()

In [ ]:
from johnsnowlabs import nlp, medical

# After uploading your license run this to install all licensed Python Wheels and pre-download Jars the Spark Session JVM
nlp.install()

In [ ]:
from johnsnowlabs import nlp, medical
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Automatically load license data and start a session with all jars user has access to
spark = nlp.start()

In [5]:
spark

## Healthcare NLP for Data Scientists Course

If you are not familiar with the components in this notebook, you can check [Healthcare NLP for Data Scientists Udemy Course](https://www.udemy.com/course/healthcare-nlp-for-data-scientists/) and the [MOOC Notebooks](https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/Spark_NLP_Udemy_MOOC/Healthcare_NLP) for each components.

## load dataset

In [6]:
!wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Healthcare/data/petfinder-mini.csv

In [7]:
dataframe = pd.read_csv('petfinder-mini.csv')

In [8]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

In [9]:
dataframe = dataframe.drop(['AdoptionSpeed'], axis=1)

In [10]:
dataframe.head()

,Type,Age,Breed1,Gender,Color1,Color2,MaturitySize,FurLength,Vaccinated,Sterilized,Health,Fee,Description,PhotoAmt,target
0,Cat,3,Tabby,Male,Black,White,Small,Short,No,No,Healthy,100,Nibble is a 3+ month old ball of cuteness. He ...,1,1
1,Cat,1,Domestic Medium Hair,Male,Black,Brown,Medium,Medium,Not Sure,Not Sure,Healthy,0,I just found it alone yesterday near my apartm...,2,1
2,Dog,1,Mixed Breed,Male,Brown,White,Medium,Medium,Yes,No,Healthy,0,Their pregnant mother was dumped by her irresp...,7,1
3,Dog,4,Mixed Breed,Female,Black,Brown,Medium,Short,Yes,No,Healthy,150,"Good guard dog, very alert, active, obedience ...",8,1
4,Dog,1,Mixed Breed,Male,Black,No Color,Medium,Short,No,No,Healthy,0,This handsome yet cute boy is up for adoption....,3,1

In [11]:
dataframe.columns

Index(['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize',
       'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'Description',
       'PhotoAmt', 'target'],
      dtype='object')

In [12]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11537 entries, 0 to 11536
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          11537 non-null  object
 1   Age           11537 non-null  int64
 2   Breed1        11537 non-null  object
 3   Gender        11537 non-null  object
 4   Color1        11537 non-null  object
 5   Color2        11537 non-null  object
 6   MaturitySize  11537 non-null  object
 7   FurLength     11537 non-null  object
 8   Vaccinated    11537 non-null  object
 9   Sterilized    11537 non-null  object
 10  Health        11537 non-null  object
 11  Fee           11537 non-null  int64
 12  Description   11528 non-null  object
 13  PhotoAmt      11537 non-null  int64
 14  target        11537 non-null  int64
dtypes: int64(4), object(11)
memory usage: 1.3+ MB

In [13]:
dataframe.target.value_counts()

target
1    8457
0    3080
Name: count, dtype: int64

In [14]:
dataframe.Description = dataframe.Description.fillna('- no description -')

## Featurize with Sklearn Column Transformer

In [15]:
from sklearn.compose import make_column_transformer
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

column_trans = make_column_transformer(
     (OneHotEncoder(), ['Type', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize',
       'FurLength', 'Vaccinated', 'Sterilized', 'Health']),
     (TfidfVectorizer(max_features=100,  norm='l2', ngram_range=(1, 3)), 'Description'),
     remainder=StandardScaler())

X = column_trans.fit_transform(dataframe.drop(['target'], axis=1))

y = dataframe.target

In [16]:
y.nunique()

2

In [17]:
X.shape

(11537, 302)

In [18]:
input_dim = X.shape[1]

In [19]:
input_dim

302

In [20]:
df = pd.DataFrame.sparse.from_spmatrix(X)

df.columns = ['col_{}'.format(i) for i in range(input_dim)]

df['target']= y

df.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_293,col_294,col_295,col_296,col_297,col_298,col_299,col_300,col_301,target
0,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-0.452479,0.950288,-0.829762,1
1,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-0.555981,-0.299388,-0.511871,1
2,0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-0.555981,-0.299388,1.077583,1
3,0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.22648,0,-0.400729,1.575125,1.395473,1
4,0,1.0,0,0,0,0,0,0,0,0,...,0,0.198113,0,0.133816,0.181835,0,-0.555981,-0.299388,-0.19398,1

## Train with Spark NLP Generic Classifier

**Building a pipeline**

The FeaturesAssembler is used to collect features from different columns. It can collect features from single value columns (anything which can be cast to a float, if casts fails then the value is set to 0), array columns or SparkNLP annotations (if the annotation is an embedding, it takes the embedding, otherwise tries to cast the 'result' field). The output of the transformer is a FEATURE_VECTOR annotation (the numeric vector is in the 'embeddings' field).

The GenericClassifierApproach takes FEATURE_VECTOR annotations as input, classifies them and outputs CATEGORY annotations. The operation of the classifier is controled by the following methods:

*setEpochsNumber(int)* - Determines how many epochs the model is trained.

*setBatchSize(int)* - Sets the batch size during training.

*setLearningRate(float)* - Sets the learning rate.

*setValidationSplit(float)* - Sets the proportion of examples in the training set used for validation.

*setModelFile(string)* - Loads a model from the specified location and uses it instead of the default model.

*setFixImbalance(boolean)* - If set to true, it tries to balance the training set by weighting the classes according to the inverse of the examples they have.

*setFeatureScaling(string)* - Normalizes the feature factors using the specified method ("zscore", "minmax" or empty for no normalization).

*setOutputLogsPath(string)* - Sets the path to a folder where logs of training progress will be saved. No logs are generated if no path is specified.

In [21]:
spark_df = spark.createDataFrame(df)
spark_df.select(spark_df.columns[-10:]).show(2)

+-------+-------+-------+-------+-------+-------+-------------------+--------------------+-------------------+------+
|col_293|col_294|col_295|col_296|col_297|col_298|            col_299|             col_300|            col_301|target|
+-------+-------+-------+-------+-------+-------+-------------------+--------------------+-------------------+------+
|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|-0.4524794726808656|  0.9502875792756131|-0.8297616989552165|     1|
|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0| -0.555981017719065|-0.29938816657135553|-0.5118709929431844|     1|
+-------+-------+-------+-------+-------+-------+-------------------+--------------------+-------------------+------+
only showing top 2 rows

In [22]:
import pyspark.sql.functions as F
spark_df.groupBy("target") \
    .count() \
    .orderBy(F.col("count").desc()) \
    .show()

+------+-----+
|target|count|
+------+-----+
|     1| 8457|
|     0| 3080|
+------+-----+

In [23]:
(training_data, test_data) = spark_df.randomSplit([0.8, 0.2], seed = 100)

print("Training Dataset Count: " + str(training_data.count()))
print("Test Dataset Count: " + str(test_data.count()))

Training Dataset Count: 9185
Test Dataset Count: 2352

## Create a custom DL architecture with TF

In [ ]:
!pip install -q tensorflow==2.12.0 tensorflow_addons

In [25]:
graph_folder = "gc_graph"

gc_graph_builder = medical.TFGraphBuilder()\
    .setModelName("generic_classifier")\
    .setInputCols(["features"])\
    .setLabelColumn("target")\
    .setHiddenLayers([300, 200, 100])\
    .setHiddenAct("tanh")\
    .setHiddenActL2(True)\
    .setBatchNorm(True)\
    .setGraphFolder(graph_folder)\
    .setGraphFile("gcf_graph.pb")

In [26]:
'''
# Create custom graph

# If this method is used, graph folder should be added to training
# model as `.setGraphFolder(graph_folder_path)`

!mkdir gc_graph

medical.tf_graph.print_model_params("generic_classifier")

DL_params = {"input_dim": input_dim,
             "output_dim": y.nunique(),
             "hidden_layers": [300, 200, 100],
             "hidden_act": "tanh",
             'hidden_act_l2':1,
             'batch_norm':1}


medical.tf_graph.build("generic_classifier",
               build_params=DL_params,
               model_location="/content/gc_graph",
               model_filename="auto")
'''

'''
# or just use the one we already have in the repo

!wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Healthcare/generic_classifier_graph/pet.in1202D.out2.pb -P /content/gc_graph
'''

'\n# or just use the one we already have in the repo\n\n!wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Healthcare/generic_classifier_graph/pet.in1202D.out2.pb -P /content/gc_graph\n'

In [27]:
!mkdir logs

features_asm = medical.FeaturesAssembler()\
    .setInputCols(['col_{}'.format(i) for i in range(X.shape[1])])\
    .setOutputCol("features")

gen_clf = medical.GenericClassifierApproach()\
    .setLabelColumn("target")\
    .setInputCols("features")\
    .setOutputCol("prediction")\
    .setModelFile(f"{graph_folder}/gcf_graph.pb")\
    .setEpochsNumber(50)\
    .setBatchSize(100)\
    .setFeatureScaling("zscore")\
    .setFixImbalance(True)\
    .setLearningRate(0.002)\
    .setOutputLogsPath("logs")\
    .setValidationSplit(0.2) # keep 20% of the data for validation purposes

clf_Pipeline = nlp.Pipeline(
    stages=[
        features_asm,
        gc_graph_builder,
        gen_clf
])

In [28]:
pip install git+https://github.com/tensorflow/addons.git

Collecting git+https://github.com/tensorflow/addons.git
  Cloning https://github.com/tensorflow/addons.git to /tmp/pip-req-build-rsbx4pgt
  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/addons.git /tmp/pip-req-build-rsbx4pgt
  Resolved https://github.com/tensorflow/addons.git to commit d208d752e98c310280938efa939117bf635a60a8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typeguard<3.0.0,>=2.7 (from tensorflow-addons==0.23.0.dev0)
  Downloading typeguard-2.13.3-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow-addons==0.23.0.dev0) (26.2)
Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Building wheels for collected packages: tensorflow-addons
  Building wheel for tensorflow-addons (pyproject.toml) ... done
  Created wheel for tensorflow-addons: filename=tensorflow_addons-0.23.0.dev0-cp312-cp312-linux_x86_64.whl size=512725 sha256=782d7b33d140b7bd64620c3e802ab93004505f534539d8844b6769a604f9a01e
  Stored in directory: /tmp/pip-ephem-wheel-cache-q9m93tj_/wheels/c2/bd/8a/a635c31aad62c03fa940b8ad0555a23abe899b540bedf9e33d
Successfully built tensorflow-addons
Installing collected packages: typeguard, tensorflow-addons
  Attempting uninstall: typeguard
    Found existing installation: typeguard 4.5.2
    Uninstalling typeguard-4.5.2:
      Successfully uninstalled typeguard-4.5.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inflect 7.5.0 requires typeguard>=4.0.1, but you have typeguard 2.13.3 which is incompatible.
Successfully installed tensorflow-addons-0.23.0.dev0 typeguard-2.13.3

In [29]:
%%time

# train 50 epochs (takes around 1 min)

clf_model = clf_Pipeline.fit(training_data)

TF Graph Builder configuration:
Model name: generic_classifier
Graph folder: gc_graph
Graph file name: gcf_graph.pb
Build params: {'input_dim': 302, 'output_dim': 2, 'hidden_layers': [300, 200, 100], 'hidden_act': 'tanh', 'hidden_act_l2': True, 'batch_norm': True}
generic_classifier graph exported to gc_graph/gcf_graph.pb
CPU times: user 4.25 s, sys: 908 ms, total: 5.16 s
Wall time: 28.3 s

In [30]:
import os
log_file_name = os.listdir("logs")[0]

with open("logs/"+log_file_name, "r") as log_file :
    print(log_file.read())

Training 50 epochs
Epoch 1/50	0.58s	Loss: 19.22049	ACC: 0.62783784	Validation ACC: 0.67610234
Epoch 2/50	0.26s	Loss: 16.226648	ACC: 0.71379495	Validation ACC: 0.67229176
Epoch 3/50	0.23s	Loss: 14.658832	ACC: 0.7482094	Validation ACC: 0.6995101
Epoch 4/50	0.24s	Loss: 12.788274	ACC: 0.7915202	Validation ACC: 0.6810016
Epoch 5/50	0.23s	Loss: 10.433129	ACC: 0.8451353	Validation ACC: 0.675558
Epoch 6/50	0.22s	Loss: 8.635012	ACC: 0.87874997	Validation ACC: 0.6962439
Epoch 7/50	0.22s	Loss: 6.4666004	ACC: 0.91388494	Validation ACC: 0.70658684
Epoch 8/50	0.21s	Loss: 4.8413877	ACC: 0.9411825	Validation ACC: 0.71094173
Epoch 9/50	0.22s	Loss: 3.4297957	ACC: 0.9617454	Validation ACC: 0.7022319
Epoch 10/50	0.21s	Loss: 2.6448457	ACC: 0.97308564	Validation ACC: 0.7267284
Epoch 11/50	0.21s	Loss: 1.7571898	ACC: 0.98378414	Validation ACC: 0.71039736
Epoch 12/50	0.21s	Loss: 1.3142022	ACC: 0.9870272	Validation ACC: 0.7245509
Epoch 13/50	0.21s	Loss: 0.99131453	ACC: 0.9910811	Validation ACC: 0.72346216
Epoch 14/50	0.21s	Loss: 0.8704001	ACC: 0.9924328	Validation ACC: 0.7196516
Epoch 15/50	0.22s	Loss: 0.71943855	ACC: 0.993784	Validation ACC: 0.72727275
Epoch 16/50	0.22s	Loss: 0.77504027	ACC: 0.99323213	Validation ACC: 0.7087643
Epoch 17/50	0.21s	Loss: 1.5945771	ACC: 0.9825564	Validation ACC: 0.7207403
Epoch 18/50	0.22s	Loss: 1.9349785	ACC: 0.97644156	Validation ACC: 0.69678825
Epoch 19/50	0.21s	Loss: 2.2832503	ACC: 0.96958345	Validation ACC: 0.70277625
Epoch 20/50	0.21s	Loss: 1.7320403	ACC: 0.98025906	Validation ACC: 0.697877
Epoch 21/50	0.21s	Loss: 0.9261229	ACC: 0.9902591	Validation ACC: 0.7016875
Epoch 22/50	0.21s	Loss: 0.5674528	ACC: 0.99418926	Validation ACC: 0.7278171
Epoch 23/50	0.21s	Loss: 0.4459709	ACC: 0.995946	Validation ACC: 0.7196516
Epoch 24/50	0.21s	Loss: 0.19157854	ACC: 0.9982434	Validation ACC: 0.7223734
Epoch 25/50	0.20s	Loss: 0.21238315	ACC: 0.9977027	Validation ACC: 0.71584105
Epoch 26/50	0.20s	Loss: 0.2343085	ACC: 0.9977027	Validation ACC: 0.72400653
Epoch 27/50	0.20s	Loss: 0.17661473	ACC: 0.99782676	Validation ACC: 0.726184
Epoch 28/50	0.21s	Loss: 0.2910499	ACC: 0.9977027	Validation ACC: 0.7229178
Epoch 29/50	0.21s	Loss: 0.27828085	ACC: 0.9967569	Validation ACC: 0.726184
Epoch 30/50	0.22s	Loss: 0.25893545	ACC: 0.9971623	Validation ACC: 0.7212847
Epoch 31/50	0.22s	Loss: 0.23153731	ACC: 0.9974324	Validation ACC: 0.7131192
Epoch 32/50	0.22s	Loss: 0.1798173	ACC: 0.9985135	Validation ACC: 0.7223734
Epoch 33/50	0.24s	Loss: 0.17176127	ACC: 0.9981083	Validation ACC: 0.72400653
Epoch 34/50	0.23s	Loss: 0.27890217	ACC: 0.9966104	Validation ACC: 0.7212847
Epoch 35/50	0.23s	Loss: 0.5008855	ACC: 0.99608135	Validation ACC: 0.70821995
Epoch 36/50	0.23s	Loss: 2.379084	ACC: 0.97019154	Validation ACC: 0.69297767
Epoch 37/50	0.22s	Loss: 7.5446644	ACC: 0.90587825	Validation ACC: 0.6804573
Epoch 38/50	0.22s	Loss: 5.183156	ACC: 0.9290199	Validation ACC: 0.709853
Epoch 39/50	0.22s	Loss: 1.9282539	ACC: 0.97836727	Validation ACC: 0.7000544
Epoch 40/50	0.22s	Loss: 0.95336163	ACC: 0.98986506	Validation ACC: 0.7267284
Epoch 41/50	0.21s	Loss: 0.3516669	ACC: 0.99743253	Validation ACC: 0.72727275
Epoch 42/50	0.21s	Loss: 0.18464468	ACC: 0.9985137	Validation ACC: 0.7354382
Epoch 43/50	0.21s	Loss: 0.1263169	ACC: 0.9989189	Validation ACC: 0.72999454
Epoch 44/50	0.21s	Loss: 0.1616016	ACC: 0.9983672	Validation ACC: 0.72945017
Epoch 45/50	0.20s	Loss: 0.14531203	ACC: 0.99864876	Validation ACC: 0.72727275
Epoch 46/50	0.21s	Loss: 0.21387152	ACC: 0.9979731	Validation ACC: 0.7250953
Epoch 47/50	0.20s	Loss: 0.19236322	ACC: 0.9979731	Validation ACC: 0.7278171
Epoch 48/50	0.20s	Loss: 0.124105856	ACC: 0.99905413	Validation ACC: 0.7310833
Epoch 49/50	0.20s	Loss: 0.15979083	ACC: 0.9985136	Validation ACC: 0.7327164
Epoch 50/50	0.20s	Loss: 0.0974727	ACC: 0.9990541	Validation ACC: 0.726184
Training completed.

In [31]:
pred_df = clf_model.transform(test_data)

In [32]:
pred_df.select('target','prediction.result').show()

+------+------+
|target|result|
+------+------+
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     0|   [1]|
|     1|   [0]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [0]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     1|   [1]|
|     0|   [0]|
|     1|   [1]|
+------+------+
only showing top 20 rows

In [33]:
preds_df = pred_df.select('target','prediction.result').toPandas()

# Let's explode the array and get the item(s) inside of result column out
preds_df['result'] = preds_df['result'].apply(lambda x : int(x[0]))

In [34]:
preds_df.sample(10)

      target  result
1181       1       1
2207       1       1
532        1       1
1628       1       1
2255       1       1
2152       1       1
434        1       1
1986       1       0
1513       1       1
812        1       1

In [35]:
# We are going to use sklearn to evalute the results on test dataset
from sklearn.metrics import classification_report, accuracy_score

print (classification_report(preds_df['target'], preds_df['result'], digits=4))

print (accuracy_score(preds_df['target'], preds_df['result']))

              precision    recall  f1-score   support

           0     0.4907    0.4746    0.4825       611
           1     0.8177    0.8271    0.8224      1741

    accuracy                         0.7355      2352
   macro avg     0.6542    0.6509    0.6525      2352
weighted avg     0.7328    0.7355    0.7341      2352

0.7355442176870748

## get prediction for random input

In [36]:
pd.DataFrame([dataframe.loc[5191].to_dict()])

,Type,Age,Breed1,Gender,Color1,Color2,MaturitySize,FurLength,Vaccinated,Sterilized,Health,Fee,Description,PhotoAmt,target
0,Dog,2,Mixed Breed,Female,Black,Brown,Medium,Medium,Yes,Yes,Healthy,10,Friendly and pampered female puppy looking for...,2,1

In [37]:
input_X = column_trans.transform(pd.DataFrame([dataframe.loc[0].to_dict()]).drop(['target'], axis=1))

input_y = dataframe.target[0]

In [38]:
input_df = pd.DataFrame.sparse.from_spmatrix(input_X)

input_df.columns = ['col_{}'.format(i) for i in range(input_X.shape[1])]

input_df['target']= input_y

input_df.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_293,col_294,col_295,col_296,col_297,col_298,col_299,col_300,col_301,target
0,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,-0.452479,0.950288,-0.829762,1

In [39]:
input_spark_df = spark.createDataFrame(input_df)
input_spark_df.show(2)

+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------+------------------+------------------+-------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+------------------+-------+-------------------+------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------------------+-------+------------------+-------------------+-----------------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+------+
|col_0|col_1|col_2|col_3|col_4|col_5|col_6|col_7|col_8|col_9|col_10|col_11|col_12|col_13|col_14|col_15|col_16|col_17|col_18|col_19|col_20|col_21|col_22|col_23|col_24|col_25|col_26|col_27|col_28|col_29|col_30|col_31|col_32|col_33|col_34|col_35|col_36|col_37|col_38|col_39|col_40|col_41|col_42|col_43|col_44|col_45|col_46|col_47|col_48|col_49|col_50|col_51|col_52|col_53|col_54|col_55|col_56|col_57|col_58|col_59|col_60|col_61|col_62|col_63|col_64|col_65|col_66|col_67|col_68|col_69|col_70|col_71|col_72|col_73|col_74|col_75|col_76|col_77|col_78|col_79|col_80|col_81|col_82|col_83|col_84|col_85|col_86|col_87|col_88|col_89|col_90|col_91|col_92|col_93|col_94|col_95|col_96|col_97|col_98|col_99|col_100|col_101|col_102|col_103|col_104|col_105|col_106|col_107|col_108|col_109|col_110|col_111|col_112|col_113|col_114|col_115|col_116|col_117|col_118|col_119|col_120|col_121|col_122|col_123|col_124|col_125|col_126|col_127|col_128|col_129|col_130|col_131|col_132|col_133|col_134|col_135|col_136|col_137|col_138|col_139|col_140|col_141|col_142|col_143|col_144|col_145|col_146|col_147|col_148|col_149|col_150|col_151|col_152|col_153|col_154|col_155|col_156|col_157|col_158|col_159|col_160|col_161|col_162|col_163|col_164|col_165|col_166|col_167|col_168|col_169|col_170|col_171|col_172|col_173|col_174|col_175|col_176|col_177|col_178|col_179|col_180|col_181|col_182|col_183|col_184|col_185|col_186|col_187|col_188|col_189|col_190|col_191|col_192|col_193|col_194|col_195|col_196|col_197|col_198|col_199|col_200|col_201|col_202|col_203|col_204|           col_205|col_206|            col_207|col_208|col_209|col_210|            col_211|col_212|col_213|col_214|            col_215|col_216|            col_217|col_218|col_219|col_220|col_221|col_222|col_223|            col_224|col_225|col_226|col_227|col_228|col_229|col_230|col_231|            col_232|           col_233|            col_234|col_235|col_236|col_237|col_238|col_239|col_240|col_241|col_242|           col_243|col_244|            col_245|col_246|col_247|col_248|col_249|           col_250|           col_251|col_252|col_253|col_254|col_255|            col_256|col_257|            col_258|col_259|col_260|           col_261|col_262|            col_263|           col_264|col_265|col_266|col_267|col_268|col_269|col_270|            col_271|col_272|col_273|            col_274|col_275|col_276|col_277|            col_278|col_279|            col_280|            col_281|col_282|           col_283|            col_284|          col_285|col_286|col_287|col_288|col_289|           col_290|col_291|col_292|col_293|col_294|col_295|col_296|col_297|col_298|            col_299|           col_300|            col_301|target|
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------+------------------+------------------+-------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+------------------+-------+-------------------+------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------------------+-------+------------------+-------------------+-----------------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+------+
|  1.0|  0.0|  0.0|  0.0|  0.0|  0.0|  0.0|  0.0|  0.0|  0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|   0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    1.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    1.0|    1.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    1.0|    0.0|    0.0|    0.0|    1.0|    0.0|    0.0|    1.0|    1.0|    0.0|    0.0|    1.0|    0.0|    0.0|    1.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|0.1479066698321713|    0.0|0.14190121603222797|    0.0|    0.0|    0.0|0.13944594996798249|    0.0|    0.0|    0.0|0.32658388065734517|    0.0|0.36344974543439384|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|0.17451245434188148|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|0.13723100321630186|0.1315239445466759|0.15807938231468013|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|0.2222896574945158|    0.0|0.16411338759316996|    0.0|    0.0|    0.0|    0.0|0.1462525962887284|0.1515935541017556|    0.0|    0.0|    0.0|    0.0|0.17182477736803126|    0.0|0.13776502923519987|    0.0|    0.0|0.2836093435371882|    0.0|0.22099159568363785|0.1515935541017556|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|0.14490710928857284|    0.0|    0.0|0.15886943350491084|    0.0|    0.0|    0.0|0.17020231643621125|    0.0|0.19246519270780893|0.19078292304252875|    0.0|0.1324271348504037|0.17663873912979308|0.151246117308006|    0.0|    0.0|    0.0|    0.0|0.2578425424693541|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|    0.0|-0.4524794726808656|0.9502875792756131|-0.8297616989552165|     1|
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------+-------+-------+-------+------------------+------------------+-------+-------+-------+-------+-------------------+-------+-------------------+-------+-------+------------------+-------+-------------------+------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------------------+-------------------+-------+------------------+-------------------+-----------------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------------------+------+

In [40]:
clf_model.transform(input_spark_df).select('target','prediction.result').show()

+------+------+
|target|result|
+------+------+
|     1|   [1]|
+------+------+

# Case Study: Alexa Review Classification

In [41]:
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Public/data/amazon_alexa.tsv

In [42]:

df = pd.read_csv('amazon_alexa.tsv', sep='\t')
df

,rating,date,variation,verified_reviews,feedback
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1
4,5,31-Jul-18,Charcoal Fabric,Music,1
...,...,...,...,...,...
3145,5,30-Jul-18,Black Dot,"Perfect for kids, adults and everyone in betwe...",1
3146,5,30-Jul-18,Black Dot,"Listening to music, searching locations, check...",1
3147,5,30-Jul-18,Black Dot,"I do love these things, i have them running my...",1
3148,5,30-Jul-18,White Dot,Only complaint I have is that the sound qualit...,1
3149,4,29-Jul-18,Black Dot,Good,1

In [43]:
df.verified_reviews = df.verified_reviews.str.lower()

In [44]:
df.feedback.value_counts()

feedback
1    2893
0     257
Name: count, dtype: int64

In [45]:
from sklearn.compose import make_column_transformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df['verified_reviews'] = df['verified_reviews'].fillna('')
df['rating'] = df['rating'].fillna('unknown')
df['variation'] = df['variation'].fillna('unknown')


column_trans = make_column_transformer(
    (OneHotEncoder(), ['rating', 'variation']),
    (TfidfVectorizer(max_features=1000, norm='l2', ngram_range=(1, 3)), 'verified_reviews')
)

X = column_trans.fit_transform(df.drop(['feedback'], axis=1))
y = df['feedback']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

Accuracy: 1.0

In [46]:
sdf = pd.DataFrame.sparse.from_spmatrix(X)

sdf.columns = ['col_{}'.format(i) for i in range(X.shape[1])]

sdf['feedback']= y

sdf.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_1012,col_1013,col_1014,col_1015,col_1016,col_1017,col_1018,col_1019,col_1020,feedback
0,0,0,0,0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,1.0,0,0,0,0,0,0,...,0,0.324472,0,0.149662,0,0,0,0,0,1
3,0,0,0,0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,1.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [47]:
input_spark_df = spark.createDataFrame(sdf)

In [48]:
input_spark_df.show(5)

+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------------+-------------------+-------------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------------+------+------+------+------+------+------+------+------+------+-------------------+------+------+------+------+------+------+------+------+------+------+-------------------+-------------------+------+------+------+------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------------------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-----------------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------------------+------------------+-------+-------+-------+-------+------------------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------------------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------------------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+------------------+-------------------+-------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------------------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+--------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+------------------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------------------+-------+-------+-------+-------+-------+-------+-------+-------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------------------+--------+-------------------+--------+--------+--------+--------+--------+--------+
|col_0|col_1|col_2|col_3|col_4|col_5|col_6|col_7|col_8|col_9|col_10|col_11|col_12|col_13|col_14|col_15|col_16|col_17|col_18|col_19|col_20|col_21|col_22|col_23|col_24|col_25|col_26|col_27|             col_28|             col_29|             col_30|col_31|col_32|col_33|col_34|col_35|col_36|col_37|col_38|col_39|col_40|col_41|col_42|col_43|col_44|col_45|col_46|col_47|col_48|             col_49|col_50|col_51|col_52|col_53|col_54|col_55|col_56|col_57|col_58|col_59|col_60|col_61|col_62|col_63|col_64|col_65|col_66|col_67|col_68|col_69|col_70|col_71|col_72|             col_73|col_74|col_75|col_76|col_77|col_78|col_79|col_80|col_81|col_82|             col_83|col_84|col_85|col_86|col_87|col_88|col_89|col_90|col_91|col_92|col_93|             col_94|             col_95|col_96|col_97|col_98|col_99|col_100|col_101|col_102|            col_103|col_104|col_105|col_106|col_107|col_108|col_109|            col_110|col_111|col_112|col_113|col_114|col_115|col_116|col_117|col_118|col_119|col_120|col_121|col_122|col_123|           col_124|col_125|col_126|col_127|col_128|col_129|col_130|col_131|col_132|col_133|col_134|col_135|col_136|            col_137|            col_138|            col_139|col_140|col_141|col_142|col_143|col_144|col_145|col_146|col_147|col_148|col_149|col_150|col_151|col_152|col_153|col_154|col_155|col_156|col_157|col_158|col_159|            col_160|col_161|col_162|col_163|col_164|col_165|col_166|col_167|col_168|col_169|col_170|col_171|col_172|col_173|            col_174|col_175|col_176|col_177|col_178|col_179|col_180|col_181|col_182|col_183|col_184|col_185|col_186|col_187|col_188|col_189|col_190|col_191|col_192|col_193|col_194|col_195|col_196|            col_197|col_198|col_199|col_200|col_201|col_202|col_203|col_204|col_205|col_206|col_207|col_208|col_209|col_210|col_211|col_212|col_213|col_214|col_215|col_216|col_217|col_218|col_219|col_220|col_221|col_222|col_223|col_224|col_225|col_226|col_227|col_228|col_229|col_230|col_231|col_232|col_233|col_234|col_235|col_236|col_237|col_238|col_239|col_240|col_241|col_242|col_243|col_244|col_245|col_246|col_247|col_248|            col_249|col_250|col_251|col_252|col_253|col_254|col_255|col_256|col_257|col_258|col_259|col_260|col_261|col_262|col_263|col_264|col_265|col_266|col_267|col_268|col_269|col_270|col_271|col_272|col_273|col_274|col_275|col_276|col_277|col_278|col_279|col_280|col_281|col_282|col_283|col_284|col_285|col_286|col_287|col_288|col_289|col_290|col_291|col_292|col_293|col_294|col_295|col_296|col_297|col_298|col_299|col_300|col_301|col_302|col_303|           col_304|col_305|col_306|            col_307|col_308|col_309|col_310|            col_311|col_312|col_313|col_314|col_315|col_316|col_317|col_318|col_319|col_320|col_321|col_322|col_323|col_324|col_325|col_326|col_327|col_328|col_329|col_330|col_331|col_332|col_333|            col_334|           col_335|col_336|col_337|col_338|col_339|col_340|col_341|col_342|col_343|col_344|            col_345|col_346|col_347|col_348|col_349|col_350|col_351|col_352|            col_353|col_354|col_355|            col_356|col_357|col_358|            col_359|col_360|col_361|col_362|col_363|col_364|col_365|col_366|col_367|col_368|col_369|col_370|col_371|col_372|col_373|col_374|            col_375|col_376|col_377|col_378|col_379|col_380|col_381|col_382|col_383|col_384|col_385|col_386|col_387|col_388|col_389|col_390|col_391|col_392|col_393|col_394|col_395|col_396|col_397|col_398|col_399|col_400|col_401|col_402|col_403|col_404|col_405|col_406|col_407|col_408|col_409|col_410|col_411|col_412|col_413|col_414|col_415|col_416|col_417|col_418|col_419|            col_420|col_421|col_422|col_423|col_424|col_425|col_426|col_427|col_428|col_429|col_430|col_431|col_432|col_433|col_434|col_435|col_436|col_437|col_438|col_439|col_440|col_441|col_442|col_443|col_444|col_445|col_446|col_447|col_448|col_449|col_450|col_451|col_452|col_453|col_454|col_455|col_456|col_457|col_458|col_459|col_460|col_461|col_462|col_463|col_464|            col_465|            col_466|            col_467|col_468|col_469|col_470|col_471|col_472|col_473|col_474|col_475|col_476|col_477|col_478|col_479|col_480|col_481|col_482|col_483|col_484|col_485|col_486|col_487|col_488|col_489|          col_490|            col_491|col_492|col_493|col_494|            col_495|col_496|col_497|col_498|col_499|            col_500|           col_501|col_502|col_503|col_504|col_505|           col_506|           col_507|col_508|col_509|col_510|col_511|col_512|col_513|col_514|col_515|col_516|col_517|col_518|col_519|col_520|col_521|col_522|col_523|col_524|col_525|col_526|col_527|col_528|col_529|col_530|col_531|col_532|           col_533|col_534|col_535|col_536|            col_537|col_538|col_539|col_540|            col_541|col_542|col_543|col_544|col_545|col_546|col_547|col_548|col_549|col_550|col_551|col_552|col_553|col_554|col_555|col_556|col_557|col_558|col_559|col_560|col_561|col_562|col_563|col_564|           col_565|col_566|col_567|col_568|col_569|col_570|col_571|col_572|col_573|col_574|col_575|           col_576|            col_577|col_578|col_579|col_580|col_581|col_582|col_583|            col_584|col_585|col_586|col_587|           col_588|            col_589|            col_590|            col_591|col_592|col_593|col_594|col_595|col_596|col_597|col_598|col_599|col_600|col_601|col_602|col_603|col_604|col_605|col_606|col_607|col_608|col_609|col_610|col_611|col_612|col_613|col_614|col_615|col_616|col_617|col_618|col_619|col_620|col_621|col_622|col_623|col_624|col_625|col_626|col_627|col_628|col_629|col_630|col_631|col_632|           col_633|col_634|            col_635|            col_636|col_637|col_638|col_639|col_640|col_641|col_642|col_643|col_644|col_645|col_646|col_647|col_648|col_649|col_650|col_651|col_652|col_653|col_654|col_655|col_656|col_657|col_658|col_659|col_660|col_661|col_662|col_663|col_664|col_665|col_666|col_667|col_668|col_669|col_670|col_671|col_672|col_673|col_674|col_675|col_676|col_677|col_678|col_679|col_680|col_681|            col_682|col_683|col_684|           col_685|col_686|col_687|col_688|col_689|col_690|col_691|col_692|col_693|col_694|col_695|col_696|col_697|col_698|col_699|col_700|col_701|col_702|col_703|col_704|col_705|col_706|col_707|col_708|col_709|col_710|col_711|col_712|col_713|col_714|col_715|col_716|col_717|col_718|col_719|col_720|col_721|col_722|col_723|           col_724|col_725|col_726|col_727|col_728|            col_729|col_730|col_731|col_732|col_733|col_734|col_735|col_736|col_737|col_738|col_739|col_740|col_741|col_742|col_743|col_744|col_745|col_746|col_747|col_748|col_749|col_750|col_751|col_752|col_753|col_754|col_755|col_756|col_757|col_758|col_759|col_760|col_761|col_762|col_763|col_764|col_765|col_766|col_767|col_768|col_769|col_770|col_771|             col_772|col_773|col_774|col_775|col_776|col_777|col_778|col_779|col_780|col_781|col_782|col_783|col_784|col_785|col_786|col_787|col_788|col_789|col_790|col_791|            col_792|col_793|col_794|col_795|col_796|col_797|col_798|col_799|            col_800|col_801|col_802|col_803|col_804|col_805|col_806|col_807|col_808|col_809|col_810|col_811|col_812|col_813|col_814|col_815|col_816|col_817|col_818|col_819|col_820|col_821|col_822|col_823|            col_824|col_825|col_826|col_827|col_828|col_829|            col_830|col_831|col_832|col_833|col_834|col_835|col_836|col_837|col_838|col_839|           col_840|col_841|col_842|col_843|col_844|col_845|col_846|col_847|col_848|col_849|col_850|col_851|col_852|            col_853|col_854|col_855|col_856|col_857|col_858|col_859|col_860|col_861|col_862|col_863|col_864|col_865|col_866|col_867|col_868|col_869|col_870|col_871|col_872|col_873|col_874|col_875|col_876|col_877|col_878|col_879|col_880|col_881|col_882|col_883|col_884|col_885|            col_886|col_887|col_888|col_889|col_890|col_891|col_892|col_893|col_894|col_895|col_896|col_897|col_898|            col_899|col_900|col_901|col_902|col_903|col_904|col_905|col_906|col_907|col_908|col_909|col_910|col_911|col_912|col_913|col_914|col_915|col_916|col_917|col_918|col_919|col_920|col_921|col_922|col_923|col_924|col_925|col_926|col_927|col_928|col_929|col_930|col_931|col_932|col_933|col_934|col_935|col_936|col_937|col_938|col_939|col_940|col_941|col_942|col_943|col_944|col_945|col_946|col_947|col_948|col_949|col_950|col_951|col_952|col_953|col_954|col_955|col_956|col_957|col_958|col_959|col_960|            col_961|col_962|col_963|col_964|col_965|col_966|            col_967|col_968|col_969|col_970|col_971|col_972|col_973|           col_974|col_975|col_976|col_977|col_978|col_979|col_980|col_981|col_982|col_983|col_984|            col_985|col_986|col_987|col_988|col_989|col_990|            col_991|col_992|col_993|col_994|col_995|col_996|col_997|col_998|col_999|col_1000|col_1001|col_1002|col_1003|col_1004|col_1005|col_1006|col_1007|col_1008|col_1009|col_1010|col_1011|col_1012|           col_1013|col_1014|           col_1015|col_1016|col_1017|col_1018|col_1019|col_1020|feedback|

In [49]:
(training_data, test_data) = input_spark_df.randomSplit([0.8, 0.2], seed = 100)

print("Training Dataset Count: " + str(training_data.count()))
print("Test Dataset Count: " + str(test_data.count()))

Training Dataset Count: 2478
Test Dataset Count: 672

In [50]:
features_asm = medical.FeaturesAssembler()\
    .setInputCols(['col_{}'.format(i) for i in range(X.shape[1])])\
    .setOutputCol("features")

gc_graph_builder = medical.TFGraphBuilder()\
    .setModelName("generic_classifier")\
    .setInputCols(["features"])\
    .setLabelColumn("feedback")\
    .setHiddenLayers([300, 200, 100])\
    .setHiddenAct("tanh")\
    .setHiddenActL2(True)\
    .setBatchNorm(True)\
    .setGraphFolder(graph_folder)\
    .setGraphFile("gcf_graph.pb")\

gen_clf = medical.GenericClassifierApproach()\
    .setLabelColumn("feedback")\
    .setInputCols(["features"])\
    .setOutputCol("prediction")\
    .setModelFile(f"{graph_folder}/gcf_graph.pb")\
    .setEpochsNumber(50)\
    .setBatchSize(100)\
    .setFeatureScaling("zscore")\
    .setFixImbalance(True)\
    .setLearningRate(0.001)\
    .setOutputLogsPath("logs")\

clf_Pipeline = nlp.Pipeline(
    stages=[
        features_asm,
        gc_graph_builder,
        gen_clf
])

clf_model = clf_Pipeline.fit(training_data)

TF Graph Builder configuration:
Model name: generic_classifier
Graph folder: gc_graph
Graph file name: gcf_graph.pb
Build params: {'input_dim': 1021, 'output_dim': 2, 'hidden_layers': [300, 200, 100], 'hidden_act': 'tanh', 'hidden_act_l2': True, 'batch_norm': True}
generic_classifier graph exported to gc_graph/gcf_graph.pb

In [51]:
pred_df = clf_model.transform(test_data)

preds_df = pred_df.select('feedback','prediction.result').toPandas()

# Let's explode the array and get the item(s) inside of result column out
preds_df['result'] = preds_df['result'].apply(lambda x : int(x[0]))

# We are going to use sklearn to evalute the results on test dataset
from sklearn.metrics import classification_report, accuracy_score

print(classification_report(preds_df['feedback'], preds_df['result'], digits=4))

print(accuracy_score(preds_df['feedback'], preds_df['result']))

              precision    recall  f1-score   support

           0     0.5732    0.9592    0.7176        49
           1     0.9966    0.9438    0.9695       623

    accuracy                         0.9449       672
   macro avg     0.7849    0.9515    0.8435       672
weighted avg     0.9657    0.9449    0.9511       672

0.9449404761904762

## Extra Informations

**ExceptionHandling**

A robust exception-handling mechanism is available to ensure the process continues even if corrupted inputs are encountered. When set to True, the annotator attempts to process the data as usual. If exception-causing data (e.g., a corrupted record or document) is passed, a warning is emitted with the exception message. Processing then continues with the next record, while the rest of the batch is parsed without interruption. Note that this option may incur a performance penalty. By default, this behavior is False, meaning the process will throw an exception and terminate to inform users of the issue.


*Example*:
```python
gen_clf = medical.GenericClassifierApproach()\
    .setLabelColumn("feedback")\
    .setInputCols(["features"])\
    .setOutputCol("prediction")\
    .setModelFile(f"{graph_folder}/gcf_graph.pb")\
    .setEpochsNumber(50)\
    .setBatchSize(100)\
    .setFeatureScaling("zscore")\
    .setFixImbalance(True)\
    .setLearningRate(0.001)\
    .setOutputLogsPath("logs")\
    .setDoExceptionHandling(True)
    
```